
name: Build and Unit tests

on:
  push:
    branches: [ "develop" ]


jobs:
  build_unit_tests:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Setup .NET v 6.0
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build .Net
      run: dotnet build --no-restore
    - name: Test
      run: dotnet Homies.UnitTests/Homies.UnitTests.csproj --no-build --verbosity normal
